### ISSUE TITLE
Where to put intent-filter, under <activity?

### ISSUE THREAD

**Issue by HamiguaLu** [altera2015/usbserial#109]
Hi
Just wonder where I should put the below line in my Androidmanifest.xm

<intent-filter>
        <action android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED" />
    </intent-filter>

    <meta-data android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED"
        android:resource="@xml/device_filter" />

Thanks in advance

**Comment by tommie** [comment]
It goes as a sibling to the intent filter.

Here's an example: https://gist.github.com/tommie/568d11fecc3ab5b8fd20de39d4407389

**Comment by rockerer** [comment]
Taken directly from the [documentation](https://developer.android.com/develop/connectivity/usb/host#manifest-example)

```xml
<manifest ...>
    <uses-feature android:name="android.hardware.usb.host" />
    <uses-sdk android:minSdkVersion="12" />
    ...
    <application>
        <activity ...>
            ...
            <intent-filter>
                <action android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED" />
            </intent-filter>

            <meta-data android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED"
                android:resource="@xml/device_filter" />
        </activity>
    </application>
</manifest>
```
