### ISSUE TITLE
Thermal Printer

### ISSUE THREAD

**Issue by broberts-nybble** [altera2015/usbserial#15]
Hi, 

We are connecting to a thermal printer, however for some reason the port just won't open, do you have any advice?

**Comment by broberts-nybble** [comment]
Hi, 

We have managed to get it work as such am closing this issue, thank you for such a nice simple library.

**Comment by andrey-ushakov** [comment]
Hi @broberts-nybble ,
I have exactly same issue. Could you please explain how did you resolve the issue?
