### ISSUE TITLE
Send value as string format.

### ISSUE THREAD

**Issue by nuarneuer20** [altera2015/usbserial#18]
I need to send value to Ingenico iUC 180B device.

I need to send value as this format. This code from my C# program.

`writedata = "\x02" + "C20000000000000100s" + "\x03";`
`_serialPort.Write(writedata);`

Please help

**Comment by kgamecarter** [comment]
You can encode string by ASCII or UTF8 codec
https://api.dartlang.org/stable/1.24.3/dart-convert/ASCII-constant.html

**Comment by nuarneuer20** [comment]
Thanks bro. Already solved

**Comment by pattystars** [comment]
Do you happen to have an example on how this is completed?  

If the usb_serial write only accepts Uint8 list format doesn't it change the output every time?

How do you write to a usb without using the Uint8 List requirement?

I am attempting to send "A\r\n" to a serial device that only accepts UTF-8 and ASCII.  The Uint8 list converts the write to Uint8's and its not the same on the USB side.

Thanks,
