### ISSUE TITLE
the listDevices always null

### ISSUE THREAD

**Issue by zxj17815** [altera2015/usbserial#2]
I simulation usb COM1(android)  and usb COM2,but the listDevices always null,when I click send,
error:

`E/flutter ( 2498): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 2498): NoSuchMethodError: The method 'write' was called on null.
E/flutter ( 2498): Receiver: null
E/flutter ( 2498): Tried calling: write(Uint8Array)
E/flutter ( 2498): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter ( 2498): #1      _MyAppState.build.<anonymous closure> 
package:usb/main.dart:71
E/flutter ( 2498): <asynchronous suspension>
E/flutter ( 2498): #2      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:507`

**Comment by altera2015** [comment]
I'm guessing your solution is not simulating a USB CDC (or similar) device but directly a COM port in the Linux kernel. This code base is intended to access UART hardware connected via USB.
Can you give me more details on how you simulated your comports? What hardware vendor and product ids?

Thanks

**Comment by zxj17815** [comment]
I can connect now, but the problem is that I did not receive the returned information after sending, I do not know whether the instruction sent in the past does not belong to hex? Because I can receive the return message when I test with another software

**Comment by zxj17815** [comment]
I find the  pid=24577&vid=1027，it doesn't work;
and I use  the other pid=8963&vid=1659, it work.

**Comment by zxj17815** [comment]
oh,but I tested by FTDIs'app ,it's working, I have no idea...

**Comment by zxj17815** [comment]
Is it a driver problem? But open is ok, when I send the data, the receiving light on the control panel flashes, does it mean that the hardware and driver are ok, just my code has problems.

**Comment by altera2015** [comment]
I'm not sure, can you link your code?

**Comment by altera2015** [comment]
I've updated to the latest UsbSerial underlying library. Give it a go with 0.2.1, it might solve your trouble.

**Comment by zxj17815** [comment]
Thank you, it work now
