### ISSUE TITLE
 Not detecting CH340. But it works perfectly with FTDI

### ISSUE THREAD

**Issue by raphaelwb** [altera2015/usbserial#20]
Hello,

Not detecting CH340. But it works perfectly with FTDI. The felHR85/usbSerial dependency tells you it should work. Other apps like Google Play/Serial USB Terminal work with both cards.
Any suggestion?

Att

Raphael

**Comment by Rick-OGSS** [comment]
I am integrating with an STM board that uses CH340 USB.  Did anyone ever get this working?
Thanks for all the effort on this lib !

**Comment by JAICHANGPARK** [comment]
I had some same issues

**Comment by joybanerjee08** [comment]
I got it working by adding this to the device_filter.xml file 

> \<usb-device vendor-id="1A86" product-id="7523" \/>

Which I found here : 

![image](https://user-images.githubusercontent.com/32819925/75948760-4ad37c00-5eca-11ea-92c0-3f6cbfa51d67.png)

VID is Vendor ID and PID is Product ID.

**Comment by altera2015** [comment]
Integrated this into example.
