### ISSUE TITLE
PlatformException(UsbSerialPortAdapter)

### ISSUE THREAD

**Issue by venil7** [altera2015/usbserial#24]
I'm getting `E/flutter (29253): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(UsbSerialPortAdapter, Not an Serial device., null)`

USB device:

```
    +-o ACR1252 Dual Reader@14200000  <class AppleUSBDevice, id 0x100016c10, registered, matched, active, busy 0 (6 ms), retain 19>
```

**Comment by MinhCuongIT** [comment]
Same to you. But I don't know the way to fix it.

**Comment by altera2015** [comment]
Were you running this on IOS?

**Comment by MinhCuongIT** [comment]
I run it on Android  API 25

**Comment by ConProgramming** [comment]
I also have this... is this package abandoned, or?

**Comment by altera2015** [comment]
Strange. I pushed an update last week. Are you sure you have the latest?

**Comment by altera2015** [comment]
Not every serial adapter is supported, can you tell me exactly what hardware it is. Include the vid and pid.

**Comment by ConProgramming** [comment]
I'm trying to connect a DigitalPersona U.are.U 4500 Fingerprint Reader
VID: 1466
PID: 10

**Comment by ConProgramming** [comment]
Calling `UsbSerialDevice.isSupported(device)` on the device returns `false`, so it looks your right... thanks for the quick reply though!

**Comment by altera2015** [comment]
Yeah looking at the underlying library it is not included https://github.com/felHR85/UsbSerial
