### ISSUE TITLE
Null-terminated strings

### ISSUE THREAD

**Issue by GrantSavill** [altera2015/usbserial#26]
Hi there,

What is the proper way to use this with null-terminated strings? 

Transaction.stringTerminated(
        _port.inputStream, Uint8List.fromList([0]));

Appears to work, but of course it also splits some of the data if it happens to be 0x00.

**Comment by altera2015** [comment]
If a 0x00 is inside a null terminated string, that by definition means it is the end of the string. I believe this is as designed.
