### ISSUE TITLE
[Question] Will this work with Flutter desktop and USB/Serial Comm Port devices?

### ISSUE THREAD

**Issue by MattL-NZ** [altera2015/usbserial#28]
Will this work with Flutter desktop and USB/Serial Comm Port devices?
E.g. a basic USB relay device plugged into the desktop?

**Comment by berdroid** [comment]
Maybe head over to [Stackoverflow](http://stackoverflow.com/) to get quick and good advise on this

**Comment by altera2015** [comment]
Unfortunately not. This is android only.
