### ISSUE TITLE
Feature request: Linux and Windows Support

### ISSUE THREAD

**Issue by mjafartp** [altera2015/usbserial#35]
Add Linux and Windows support

**Comment by bretie** [comment]
If anyone is working on this and wants help share the repo.

I will start my own soon if nothing seems to be in the works.

**Comment by pepezoro** [comment]
Hope for Windows support~~

**Comment by mono424** [comment]
@ghost, cool keep us updated please :)

**Comment by altera2015** [comment]
The scope for this code is purely android. Please feel free to create your own!
