### ISSUE TITLE
Another systems support.

### ISSUE THREAD

**Issue by kamil-bit** [altera2015/usbserial#50]
Will you in the future make this plugin on another systems ? i solve this problem using processing ide . I communicate using udp and local host. Processing ide receive this udp and send Serial data. ?

**Comment by kamil-bit** [comment]
Wy now don;t support ios ? 
Why android support was possible but another systems not. I know  flutter is child of android but i would like to konow technical info

**Comment by altera2015** [comment]
the back-end library is a Java based Android only library. Could you make a iOS version probably, I'd happily accept PR's for that.

**Comment by kamil-bit** [comment]
too difficult to me:).
