### ISSUE TITLE
Any plans to update the library to android embedding v2?

### ISSUE THREAD

**Issue by MiladEsp** [altera2015/usbserial#51]
Getting `warning: [deprecation] Registrar in PluginRegistry has been deprecated` with a clean build. Looking in the code, the reason seems to be that the library is using Android embedding v1.

Any plans to update the library to Android embedding v2 any time soon?

Thanks

**Comment by altera2015** [comment]
Interesting. Looks like this details the upgrade steps:

https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

**Comment by altera2015** [comment]
Hey MiladEsp,

Please test branch https://github.com/altera2015/usbserial/tree/EmbeddingV2 

I don't have a UsbSerial device at hand so I'm limited in what I can test at the moment. Let me know if this look good.

**Comment by MiladEsp** [comment]
Thanks for the prompt response, @altera2015 .

With a clean build, I don't get those warnings anymore. Tested the example included with the library (with minor modifications specific to my device), and it's working as expected. The tested device uses the CH340 chip and the test was done on a Samsung S8.

Only thing worth mentioning, which I'm not sure if is related to your changes here, is that when I disconnect my device, I get an InterruptedException.

![image](https://user-images.githubusercontent.com/32962296/125208491-c4b70a80-e260-11eb-97e5-b349e9faad2b.png)

**Comment by altera2015** [comment]
Great, glad that works. I'll do a new release soon. 

As far as that exception trace, does it ever hit any code in my plugin? 

If so I can catch it otherwise, if it doesn't kill the app, I think we might let that one go.
