### ISSUE TITLE
Chinese arduino with Ch340 not working

### ISSUE THREAD

**Issue by UzairJawaid** [altera2015/usbserial#53]
I am trying to communicate with arduino, i have chinese version. but this code is not supporting that. though code works perfectly ok with esp32.

**Comment by MiladEsp** [comment]
I'm able to use the library with a CH340 with the following entry in the `device_filter.xml`. Add this to your file and try again. maybe it'll resolve your problem.

`<usb-device vendor-id="6790" product-id="29987" /> <!-- 0x7523: CH340 -->`

**Comment by asada03** [comment]
Thank you @MiladEsp. I will try that!
