### ISSUE TITLE
`UsbDevice.getDeviceName()` is not mapped

### ISSUE THREAD

**Issue by 4ntoine** [altera2015/usbserial#58]
[UsbDevice.getDeviceName()](https://developer.android.com/reference/android/hardware/usb/UsbDevice#getDeviceName()) is not mapped (converted) but might be needed. It usually contains some linux-style path of the device.

**Comment by altera2015** [comment]
Can you give an example of what you mean by mapped/converted?

**Comment by 4ntoine** [comment]
There is no 'name' field in dart UsbSerial class

пт, 26 нояб. 2021 г., 20:46 Ron Bessems ***@***.***>:
