### ISSUE TITLE
Communicate with FTDI 232HL at 4Mbaud

### ISSUE THREAD

**Issue by plktrr** [altera2015/usbserial#60]
I have been communicating with FTDI 232HL using the package [usb_serial](https://pub.dev/packages/usb_serial). 
Our flutter based app requires speed of 4Mbaud+.
Till 3Mbaud there are no issues but at any speeds higher than this there is no Communication with the application. I have tested the FTDI's communication on windows com port up to speed of 5Mbaud.
I had sent an email to FTDI support regarding communication at higher speeds. They had pointed out that there have been some changes in the [JAVA file](https://github.com/felHR85/UsbSerial/blob/master/usbserial/src/main/java/com/felhr/usbserial/FTDISerialDevice.java) in relation to setting the baud rate for high speed devices.
How can I achieve 4Mbaud in the flutter application using [usb_serial](https://pub.dev/packages/usb_serial)?

**Comment by altera2015** [comment]
The latest released felHR85/UsbSerial upstream is 6.1.0, this is what I am using here.
