### ISSUE TITLE
USB Port detached / attached

### ISSUE THREAD

**Issue by saguado69** [altera2015/usbserial#68]
Hi,

Is it possible to catch the event when the USB Serial Port is attached or detached (Android)?

I can see those events in the console when debuging my app.

D/UsbSerialPortAdapter( 4336): ACTION_USB_ATTACHED
D/UsbSerialPortAdapter( 4336): ACTION_USB_DETACHED

Thanks in advance for your support.

**Comment by ext-danny** [comment]
Please check this 
https://github.com/altera2015/usbserial/issues/38#issuecomment-764545049
