### ISSUE TITLE
Just a question about Transaction Class

### ISSUE THREAD

**Issue by saguado69** [altera2015/usbserial#72]
Hi @altera2015,

I'm using a subscription that listen on Transaction.stringTerminated() stream in my code, but in certain cases, I need to check if there is some data in the queue before the stringTerminated is received. Is there any way to get the data from the queue?

`// Stream transaction
      _transaction = Transaction.stringTerminated(
          comPort.inputStream as Stream<Uint8List>,
          Uint8List.fromList([13, 10]));
     
 // Stream subscription
      _subscription = _transaction.stream.listen((String data) { ...`

Thanks in advance for your support.

Santi

**Comment by altera2015** [comment]
You'd have to write your own transformer probably to do this.
