### ISSUE TITLE
Not receiving data to a non-esp32 device 

### ISSUE THREAD

**Issue by pieterbergmans** [altera2015/usbserial#74]
Hi...I'm successfully using usbserial to communicate back and forth between my Android/Flutter app and an M5Stack Fire, which is an esp32-based microcontroller.  However, when I connect my Android/Flutter app to my non esp32-based device, I can connect to the device and I can also send data but _I can't receive any data to my Android/Flutter app_. I've verified that my non esp32-based device is sending data; I've connected it to my PC and I'm receiving data to a python script.  My Flutter code follows the example code provided by usbserial. 

I don't know much about USB/serial communication and I'm having a really hard time diagnosing this.  Does anyone have any suggestions to diagnose/solve my issue? This may not even be an issue between an esp32-based device vs a non esp32-based device but I don't have any other devices lying around to further articulate the issue.

For what it's worth, these are the USB specs for my non [esp32-based](https://www.digi.com/products/embedded-systems/digi-connectcore/system-on-modules/connectcore-for-i-mx6ul#specifications) device. But, like I said, I don't know much about USB so I don't know if hardware can even ben an issue or not.

_1 x dedicated MMC 4.5/SD 3.0/SDIO Port (1-/2-4-bit), 2 x USB 2.0 OTG with PHY, 3x I2S/SAI, 1 x S/PDIF Tx/Rx, 2 x FlexCAN (2.0b), 4 x I2C, 4 x SPI, 7 x UART, 4 x Timer, 8 x PWM, 3 x Watchdog, 2 x 12-bit ADC (10 channels) with 4-wire/5-wire touch controller, up to 103 GPIOs_

Any help would be greatly appreciated.

**Comment by altera2015** [comment]
So many things could be wrong here, but not likely the library in this case.
