### ISSUE TITLE
Cant send serial commands

### ISSUE THREAD

**Issue by NetAcess** [altera2015/usbserial#84]
how to send **serial commands** like 05 which is **CTRL+E**. when I try to send like this
```
final ctrlE = String.fromCharCode(5);  // ASCII code for Ctrl+E
final command = Uint8List.fromList(ctrlE.codeUnits);
port.write(command);
```
It sends as printable characters but I want to send serial command i.e. 05.

**Comment by Mr-Jeeva** [comment]
To send CTRL + E, you have to send 
`port!.write(Uint8List.fromList("\u0005\r\n".codeUnits));`

Refer this link for more unicodes - [](https://www.techonthenet.com/unicode/chart.php)
