### ISSUE TITLE
Can we send hexa to the serial port instead of uint8? 

### ISSUE THREAD

**Issue by momyuke** [altera2015/usbserial#89]
Right now, i tried to build an app which send the hexa data to the other machine. But when I tried send the data, the package asking a Uint8List data. Is UsbSerial Package have a workaround to send the hexa data to the other machine? 

I really appreciate if you have a workaround for my problem. 

Thank you.

**Comment by altera2015** [comment]
The library supports sending uin8 (aka binary data). So it's up to the application to convert it to the proper encoding.
