### ISSUE TITLE
Error in the example

### ISSUE THREAD

**Issue by paulobreim** [altera2015/usbserial#93]
I am trying to run the example showed in the lib and I am getting the follow error.

![Screenshot_20231001_165431](https://github.com/altera2015/usbserial/assets/381594/7ab217a3-cdd7-4a89-a2ea-953ad462b4ac)

What is wrong?

tks

**Comment by rockerer** [comment]
Hi,
what platform are you running the code on? The plugin is written for android, so running it on ios, linux or windows might result in the error shown above.

**Comment by paulobreim** [comment]
I tested with linux and android.
I didn't notice it was only for Android.

Is there any prospect of it working on Windows?

tks

**Comment by rockerer** [comment]
AFAIK it is not planned, but @altera2015 might say more about the plans regarding his package.

You might be interested in using one of the following packages, which support serial communication for linux and/or windows:
- [flutter_libserialport](https://pub.dev/packages/flutter_libserialport)
- [libserialport](https://pub.dev/packages/libserialport)

If there are more people interested in extending this package to support windows / linux / ios it might be possible to do so.

**Comment by paulobreim** [comment]
TKS,  I will check this libs.

I want to make a application to share USB over the internet. I saw some apps in the internet, but nor open.

**Comment by rockerer** [comment]
Do you need a graphical userinterface for this purpose or why are you using flutter?

I think, it's easier to use a language like python, c++ or Golang to achieve this goal, if you don't need the UI. These languages might have an even better (or even native) support for the serial connection and support different approaches to share the connection over the internet.

**Comment by rockerer** [comment]
Hi @paulobreim,
we discussed about the issue and i think there is no reason to keep this issue open anymore. Would you mind closing this issue.
Thanks
