### ISSUE TITLE
ATEN adapter "Not an serial device"

### ISSUE THREAD

**Issue by magnuswikhog** [altera2015/usbserial#96]
I have a USB adapter which is not working. 

```
I/flutter (24091): PlatformException(b, Not an Serial device., null, null)
I/flutter (24091): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
I/flutter (24091): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
I/flutter (24091): <asynchronous suspension>
I/flutter (24091): #2      UsbSerial.createFromDeviceId (package:usb_serial/usb_serial.dart:433:33)
I/flutter (24091): <asynchronous suspension>
I/flutter (24091): #3      UsbDevice.create (package:usb_serial/usb_serial.dart:333:13)
```

when I try to connect to it using `device.create()`.

This is the USB device: 

```
UsbDevice: /dev/bus/usb/001/052, 67b-23a3 ATEN USB to Serial Bridge, Prolific Technology Inc. CZBBb118D15
```

When connected to a Windows machine, it is identified as `Prolific PL2303GC`. ATEN Support claims this is the newer chipset version of this USB-serial-adapter. I have two other ones that look almost identical (just slightly thicker wire) and which work with this plugin. When connected to a Windows machine, they report as `ATEN USB to serial bridge`, so clearly there is a difference in the chipset.

The adaptor works fine with other apps, for example the "Serial USB Terminal" app on Google Play, so hopefully it would be possible to get it to work with this plugin as well?

**Comment by gogus1415** [comment]
Did you solve this issue? I am using https://www.x-kom.pl/p/579298-kabel-usb-unitek-kabel-usb-c-rs-232.html?gad_source=1&gclid=CjwKCAjw17qvBhBrEiwA1rU9w06YkDGMYIjXjV-aU73S-M1YKImUIzWoyIkomoYgr6SDYCNKk7ZM3xoCeQsQAvD_BwE

**Comment by magnuswikhog** [comment]
> Did you solve this issue? I am using https://www.x-kom.pl/p/579298-kabel-usb-unitek-kabel-usb-c-rs-232.html?gad_source=1&gclid=CjwKCAjw17qvBhBrEiwA1rU9w06YkDGMYIjXjV-aU73S-M1YKImUIzWoyIkomoYgr6SDYCNKk7ZM3xoCeQsQAvD_BwE I have this same issue

Unfortunately the only way to "resolve it was to find a different USB adapter which uses FTDI chipset.

**Comment by altera2015** [comment]
Just likely unsupported by the underlying library.
